/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si_penjualan.views;

import java.awt.Rectangle;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import si_penjualan.controlpages.c_pages;
import si_penjualan.views.report.getFile;

/**
 *
 * @author SystemFive
 */
public class v_home extends javax.swing.JFrame {
    c_pages controlHome = new c_pages();
    /**
     * Creates new form v_home
     */
    public v_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mMaster = new javax.swing.JMenu();
        SMPelanggan = new javax.swing.JMenuItem();
        SMBarang = new javax.swing.JMenuItem();
        mTransaksi = new javax.swing.JMenu();
        STPembelian = new javax.swing.JMenuItem();
        mLaporan = new javax.swing.JMenu();
        SLBarang = new javax.swing.JMenuItem();
        SLPelanggan = new javax.swing.JMenuItem();
        SLTransaksi = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        mLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Utama");
        setBackground(new java.awt.Color(210, 215, 211));

        PanelUtama.setBackground(new java.awt.Color(108, 122, 137));

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(210, 215, 211));
        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mHome.setText("HOME");
        jMenuBar1.add(mHome);

        mMaster.setText("MASTER");

        SMPelanggan.setText("PELANGGAN");
        SMPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMPelangganActionPerformed(evt);
            }
        });
        mMaster.add(SMPelanggan);

        SMBarang.setText("BARANG");
        SMBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMBarangActionPerformed(evt);
            }
        });
        mMaster.add(SMBarang);

        jMenuBar1.add(mMaster);

        mTransaksi.setText("TRANSAKSI");

        STPembelian.setText("PEMBELIAN");
        STPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STPembelianActionPerformed(evt);
            }
        });
        mTransaksi.add(STPembelian);

        jMenuBar1.add(mTransaksi);

        mLaporan.setText("LAPORAN");

        SLBarang.setText("BARANG");
        SLBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLBarangActionPerformed(evt);
            }
        });
        mLaporan.add(SLBarang);

        SLPelanggan.setText("PELANGGAN");
        SLPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLPelangganActionPerformed(evt);
            }
        });
        mLaporan.add(SLPelanggan);

        SLTransaksi.setText("TRANSAKSI");
        SLTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLTransaksiActionPerformed(evt);
            }
        });
        mLaporan.add(SLTransaksi);

        jMenuBar1.add(mLaporan);

        mHelp.setText("HELP");
        jMenuBar1.add(mHelp);

        mLogout.setText("LOGOUT");
        jMenuBar1.add(mLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SMBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMBarangActionPerformed
        controlHome.barang();
    }//GEN-LAST:event_SMBarangActionPerformed

    private void SMPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMPelangganActionPerformed
        controlHome.pelanggan();
    }//GEN-LAST:event_SMPelangganActionPerformed

    private void STPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STPembelianActionPerformed
        controlHome.pembelian();
    }//GEN-LAST:event_STPembelianActionPerformed

    private void SLTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLTransaksiActionPerformed
        v_report_transaksi ob = new v_report_transaksi();
        ob.setVisible(true);
    }//GEN-LAST:event_SLTransaksiActionPerformed

    private void SLBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLBarangActionPerformed
        v_report_barang o = new v_report_barang();
        o.setVisible(true);
    }//GEN-LAST:event_SLBarangActionPerformed

    private void SLPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLPelangganActionPerformed
        v_report_pelanggan o = new v_report_pelanggan();
        o.setVisible(true);
    }//GEN-LAST:event_SLPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JMenuItem SLBarang;
    private javax.swing.JMenuItem SLPelanggan;
    private javax.swing.JMenuItem SLTransaksi;
    private javax.swing.JMenuItem SMBarang;
    private javax.swing.JMenuItem SMPelanggan;
    private javax.swing.JMenuItem STPembelian;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenu mLaporan;
    private javax.swing.JMenu mLogout;
    private javax.swing.JMenu mMaster;
    private javax.swing.JMenu mTransaksi;
    // End of variables declaration//GEN-END:variables
}
