/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si_penjualan.views;

import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import si_penjualan.entity.pelanggan;
import si_penjualan.implement.pelangganimplement;
import si_penjualan.library.libCRUD;
import si_penjualan.views.report.getFile;
import system.dbconnection;

/**
 *
 * @author SystemFive
 */
public class v_pelanggan extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    libCRUD ob = new libCRUD();
    Map param = new HashMap();
    int statusInput = -1;
    JasperReport JasRep;
    JasperDesign JasDes;
    JasperPrint JasPrint;
    pelangganimplement plServe = new pelangganimplement();
    /**
     * Creates new form v_pelanggan
     */
    public v_pelanggan() {
        initComponents();
        setJTable();
        disable_field();
        btnSimpan.setEnabled(false);
        btnBatal.setEnabled(false);
         btnDel.setEnabled(false);
    }
    public void disable_field()
    {
        txtNopel.setEnabled(false);
        txtNama.setEnabled(false);
        cmbJK.setEnabled(false);
        txtAlamat.setEnabled(false);
        txtNoTelp.setEnabled(false);
    }
    public void enable_field()
    {
        txtNopel.setEnabled(true);
        txtNama.setEnabled(true);
        cmbJK.setEnabled(true);
        txtAlamat.setEnabled(true);
        txtNoTelp.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPelanggan = new javax.swing.JTable();
        txtNopel = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        cmbJK = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setTitle("Master Pelanggan");

        listPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPelanggan);

        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });

        cmbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "= Pilih =", "Laki-Laki", "Perempuan" }));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jLabel1.setText("No Pelanggan");

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Alamat");

        jLabel5.setText("No Telepon");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnDel.setText("Hapus");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnTambah)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal))
                            .addComponent(txtNopel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJK, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnDel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnClose)
                .addGap(26, 26, 26)
                .addComponent(btnCetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNopel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnBatal)
                    .addComponent(btnDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnCetak)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getData()
    {
        int no = 0;
        try {
            List<pelanggan> record = plServe.getAll();
            int x = 0;
            no = 1;
            for (pelanggan pl : record) {
                String kode = pl.getKode();
                String nama = pl.getNama();
                String jk = pl.getJK();
                String alamat = pl.getAlamat();
                String notlp = pl.getTlp();
                Object Data[]={no++,kode,nama,jk,alamat,notlp};
                tabModel.addRow(Data);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(v_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setJTable(){
    String [] JudulKolom={"No","Kode Pelanggan","Nama","Jenis Kelamin","Alamat","No Telepon"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false,false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    listPelanggan.setModel(tabModel);
    listPelanggan.getColumnModel().getColumn(0).setPreferredWidth(30);
    getData();
    }
    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed
      public void updateRecord()
      {
        String nopel,nama,jk,alamat,notlp;
        nopel = txtNopel.getText();
        nama = txtNama.getText();
        alamat = txtAlamat.getText();
        notlp = txtNoTelp.getText();
        jk = cmbJK.getSelectedItem().toString();
        float notlpon = Float.parseFloat(notlp);
        if(jk != "= Pilih =" && alamat != "" && notlpon > 0 && Integer.parseInt(nopel) > 0)
        {
            pelanggan pl = new pelanggan();
            pl.setKode(nopel);
            pl.setNama(nama);
            pl.setJK(jk);
            pl.setAlamat(alamat);
            pl.setTlp(notlp);
            int status;
            try {
                status = plServe.update(pl);
                if(status > 0)
                {
                    JOptionPane.showMessageDialog(this,"Update Pelanggan Berhasil");
                }else{
                    JOptionPane.showMessageDialog(this,"Update Pelanggan Gagal");
                }
                setJTable();
            } catch (SQLException ex) {
                Logger.getLogger(v_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Isilah Semua Field");
        }
        cleanText();
        btnSimpan.setEnabled(false);
      }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(statusInput == -1)
        {
            saveRecord();
            disable_field();
        }else{
            updateRecord();
            disable_field();
        }
        cleanText();
        btnBatal.setEnabled(false);
    }//GEN-LAST:event_btnSimpanActionPerformed
    private void cleanText()
    {
        txtNopel.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNoTelp.setText("");
        cmbJK.setSelectedIndex(0);
    }
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    public void saveRecord()
    {
        String nopel,nama,jk,alamat,notlp;
        nopel = txtNopel.getText();
        nama = txtNama.getText();
        alamat = txtAlamat.getText();
        notlp = txtNoTelp.getText();
        jk = cmbJK.getSelectedItem().toString();
        float notlpon = Float.parseFloat(notlp);
        if(jk != "= Pilih =" && alamat != "" && notlpon > 0)
        {
            pelanggan pl = new pelanggan();
            pl.setKode(nopel);
            pl.setNama(nama);
            pl.setJK(jk);
            pl.setAlamat(alamat);
            pl.setTlp(notlp);
            try {
                
                int status = plServe.insert(pl);
                if(status > 0)
                {
                    JOptionPane.showMessageDialog(this,"Tambah Pelanggan Berhasil");

                }else{
                    JOptionPane.showMessageDialog(this,"Tambah Pelanggan Gagal");
                }
                setJTable();
            } catch (SQLException ex) {
                Logger.getLogger(v_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Isilah Semua Field");
        }
        btnSimpan.setEnabled(false);
    }
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        enable_field();
        btnSimpan.setEnabled(true);
        btnBatal.setEnabled(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        enable_field();
        statusInput = 1;
        btnBatal.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) listPelanggan.getModel();
        int selectedRowIndex = listPelanggan.getSelectedRow();
       
       txtNopel.setText(model.getValueAt(selectedRowIndex, 1).toString());
       txtNama.setText(model.getValueAt(selectedRowIndex, 2).toString());
       if(model.getValueAt(selectedRowIndex, 3).toString() == "Perempuan")
       {
           cmbJK.setSelectedIndex(2);
       }else{
           cmbJK.setSelectedIndex(1);
       }
       txtAlamat.setText(model.getValueAt(selectedRowIndex, 4).toString());
       txtNoTelp.setText(model.getValueAt(selectedRowIndex, 5).toString());
       btnSimpan.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        cleanText();
        disable_field();
        statusInput = -1;
        btnSimpan.setEnabled(false);
        btnBatal.setEnabled(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) listPelanggan.getModel();
            int selectedRowIndex = listPelanggan.getSelectedRow();
            String id = model.getValueAt(selectedRowIndex, 1).toString();
            String[] data = {id};
            pelanggan pl = new pelanggan();
            pl.setKode(id);
            int status = plServe.delete(pl);
            if(status > 0)
            {
                JOptionPane.showMessageDialog(this,"Hapus Berhasil");
            }else{
                JOptionPane.showMessageDialog(this,"Hapus Gagal");
            }
            setJTable();
            btnDel.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(v_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void listPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPelangganMouseClicked
        btnDel.setEnabled(true);
    }//GEN-LAST:event_listPelangganMouseClicked

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        getFile gf = new getFile();
        InputStream report = gf.fetch("report_pelanggan.jrxml");
        try {
            JasDes = JRXmlLoader.load(report);
            param.clear();
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasRep, param, dbconnection.getConnection());
            JasperViewer.viewReport(JasPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(v_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listPelanggan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtNopel;
    // End of variables declaration//GEN-END:variables
}
